```{r}
library(ggplot2)
library(tidyverse)
library(scales)
```


```{r}
df = read.csv("final404.csv")
dyn.load("KDE.so")
head(df)
```

R CMD SHLIB KDE.c

```{r}
KDE_c <- function(x, m) {
  n <- length(x)
  bw <- bw.nrd(x)
  xrange <- seq(min(x), max(x), length.out = m)
  a <- .C("kernal_density_gauss", as.double(x), as.integer(n), as.double(bw), as.double(xrange), as.integer(m), est=double(m))
  return(data.frame(x = xrange, fx = a[[6]]))
}
```


```{r}
to_date = function(val) {
  start = as.Date("2020-01-01")
  return(start + val)
}

to_time = function(val){
  start = strptime("00:00:00", format = "%H:%M:%S", tz = "UTC") # without UTC offset will be added upon plotting
  return(start + val) 
}
```








```{r}
x1 <- df$seconds_since_midnight
x2 <- df$days_since_newyear

KDE_seconds <- KDE_c(x1, 100)
KDE_days <- KDE_c(x2, 100)
KDE_rt <- KDE_c(df$ride_time, 1000)
```

```{r}

```


```{r}
KDE_days <- KDE_days %>%
  mutate(
    x = to_date(x)
  )

KDE_seconds <- KDE_seconds %>%
  mutate(
    x = to_time(x)
  )
```

```{r}
KDE_days
```




```{r}
ggplot(data=KDE_seconds, aes(x=x, y=fx, group=1)) +
  geom_line()+
  geom_point() +
  ggtitle("KDE of Time") +
  ylab("Density of Rides") + 
  xlab("Time of Day") +
  scale_x_datetime(labels=date_format("%H:%M"))

```
```{r}
ggplot(data=KDE_days, aes(x=x, y=fx, group=1)) +
  geom_line()+
  geom_point() +
  ggtitle("KDE of Date") +
  ylab("Density of Rides") + 
  xlab("Day")
```
```{r}
ggplot(data=KDE_rt, aes(x=x, y=fx, group=1)) +
  geom_line()+
  geom_point() +
  ggtitle("KDE of RT") +
  ylab("Density of Rides") + 
  xlab("Ride Time (s)")
```
## What does the KDE of Ride Time look like if we filter out the top 5% of values?

```{r}
df_95 <- df %>%
  top_frac(-0.95, wt = ride_time)

KDE_rt_95 <- KDE_c(df_95$ride_time, 100)
```

```{r}
ggplot(data=KDE_rt_95, aes(x=x, y=fx, group=1)) +
  geom_line()+
  geom_point() +
  ggtitle("KDE of RT - bottom 95%") +
  ylab("Density of Rides") + 
  xlab("Ride Time (s)")
```

$$Y_i \sim Poisson(\lambda_i)$$

$$log(\lambda_i) = \beta_0 + f_1(x_1) + f_2(x_2)  + ...$$












